### ISSUE TITLE
Referência ao modelo no config.pickle

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/image-processing-service#12]
@joaoherrera 

A referência ao modelo no arquivo config.pickle estava absoluta (`/model/model_frcnn.hdf5`). Alterei para a referência relativa `../model/model_frcnn.hdf5` e funciounou no docker, mas não na produção. Tive que editar manualmente no código em produção para `model/model_frcnn.hdf5`, o que não é ideal.

Como podemos fazer para que o valor no config.pickle funcione independente do ambiente em que o script está sendo rodado?

**Comment by joaoherrera** [comment]
Olá @vgeorge, Criei uma referência dinâmica para o config.pickle assim como foi feito para os arquivos .ipk

**Comment by vgeorge** [comment]
Não está funcionando. As linhas abaixo não conseguem identificar o root path no servidor em produção:

https://github.com/aetrapp/image-processing-service/blob/master/scripts/DeepLearning.py#L26-L27

Provavelmente não deu erro no Docker porque o path coincide com /model. Vou alterar os scripts para que o path seja sempre relativo ao script (`../model`) e o arquivo de modelo fique no diretório `<repository_path>/model`.

**Comment by vgeorge** [comment]
Corrigi o problema. Agora é preciso atualizar a documentação para instruir o desenvolvedor a fazer o download do modelo rodando o script `./download-model.sh`, pois este passo foi removido do Dockerfile.

**Comment by joaoherrera** [comment]
@vgeorge já existe algum documento externo referente à instalação?

**Comment by vgeorge** [comment]
No README tem os passos para a instalação, coloquei nele como fazer o download do modelo.
