### ISSUE TITLE
Amostra com possível erro na contagem  

### ISSUE THREAD

**Issue by cscheidegger** [aetrapp/image-processing-service#14]
Armadilha identificador : 2UABQYRZL8ZDL

Ao aproximar parece estar fora de foco, mas a amostra está registrada como válida, e com apenas 14 ovos

![58bc19deff870e399d489723f79ce805b1b72f35f8faed495f063162f35491b1](https://user-images.githubusercontent.com/39593264/41511724-e93a9786-7252-11e8-8767-e6255673dcb6.jpeg)

**Comment by joaoherrera** [comment]
@cscheidegger foi desenvolvida uma solução para esse problema. Em breve esse recurso será incorporado no ambiente de produção.
