### ISSUE TITLE
Imagens não processadas e sem feedback

### ISSUE THREAD

**Issue by cscheidegger** [aetrapp/image-processing-service#15]
Fotos submetidas mas não processadas 

![36087739_10160925184970157_4841820042708385792_n](https://user-images.githubusercontent.com/39593264/41825515-8c7a5b08-77f7-11e8-99b7-041ff104ed63.png)
![36175919_10160925185110157_4898515926002958336_n](https://user-images.githubusercontent.com/39593264/41825516-8c950fb6-77f7-11e8-889e-40b3de64418b.png)

**Comment by odascatolini** [comment]
@vgeorge @joaoherrera 

Vocês podem verificar por favor? Há mais usuários reclamando nos grupos, já tem alguns dias.

Obrigado

**Comment by vgeorge** [comment]
Atualizei o servidor, o problema aconteceu devido a ativação do SSL, faltou atualizar o protocolo para HTTPS na máquina em produção. Atualizei também a versão do IPS para 1.4.2 e ele vai reavaliar todas as amostras do sistema, com previsão de término às 20h. O envio de amostras foi reestabelecido.

**Comment by vgeorge** [comment]
As amostras foram recalculadas e a repetida foi removida. Se o problema persistir, por favor, reabram a issue.
