### ISSUE TITLE
Mensagem de erro ou resultado de análise

### ISSUE THREAD

**Issue by miguelpeixe** [aetrapp/image-processing-service#3]
O script deve lançar erro apenas quando houve um problema na sua execução, pois assim podemos identificar melhor erros internos do servidor.

Quando há problemas de identificação de ovos por má qualidade de imagem o script não deverá lançar erro, mas retornar um JSON que contenha informações sobre o problema, seguindo o formato:

```json
{
  "error": {
    "code": "011",
    "message": "Image too dark"    
  }
}
``` 

Para o caso de sucesso de leitura, o formato sugerido é:

```json
{
  "eggCount": 10,
  "brightness": 20,
  (outros parametros relevantes)
}
```

**Comment by joaoherrera** [comment]
Olá miguel, me desculpe pela demora, estava em viagem para as Filipinas. Vou deixar os comentários aqui pois quando é dia aqui é noite aí, não vou te pertubar no whatsapp ou qualquer outro chat altas horas da noite hehehehe. 

Não entendi muito seu request. Atualmente estou retornando JSON tanto para erros encontrados na imagem quanto para sucesso de leitura. A diferença é que para os erros encontrados ficou decidido entre eu e o Vitor que o comando exit() seja lançado, pois o fluxo do processamento deve ser interrompido. Como o código está em formato de script não há como retornar um valor, ao menos que eu crie uma função que deverá ser chamada pelo servidor. Pode ser?
