### ISSUE TITLE
Imagem docker mais enxuta

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/image-processing-service#5]
O tamanho da imagem resultante é de alguns gigas, o que dificulda seu uso em ambiente de produção. Me parece que ela é grande demais porque inclui dependências instaladas pelo `conda` que não são utilizadas.

@joaoherrera você pode avaliar se consegue modificar o `Dockerfile` para ele utilizar uma instalação linux mais leve e com apenas as dependencias que são utilizadas no serviço?

Aqui está o arquivo a ser trabalhado:

https://github.com/aetrapp/image-processing-service/blob/master/Dockerfile

**Comment by vgeorge** [comment]
Descobri que existe uma imagem mais enxuta do Anacoda, chamada Miniconda:

https://hub.docker.com/r/continuumio/miniconda3

**Comment by vgeorge** [comment]
Criei um branch `miniconda` para trabalhar nas mudanças necessárias no Dockerfile. Ao tentar avaliar uma imagem é retornado o seguinte erro:

```
Command failed: python /src/scripts/Application.py /images/5abbdf01dbbb870015d30dfd\n2018-03-28 18:31:57.010801: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
```

**Comment by joaoherrera** [comment]
Olá, Vitor
Conforme conversamos no whatsapp, essa mensagem costumava ser um warning não um erro.
Estranho que o processamento esteja sendo interrompido por essa causa.
Em qual sistema operacional você está rodando o miniconda?

**Comment by vgeorge** [comment]
Para testar você precisa dar um checkout no branch `miniconda`, lá está a imagem que estou trabalhando:

https://github.com/aetrapp/image-processing-service/tree/miniconda

Depois de dar um checkout você precisa reconstruir a imagem com `docker-compose build`.

**Comment by joaoherrera** [comment]
Vitor, um outro problema ocorre ao executar o comando `docker-compose up` tanto no branch miniconda como no master: [https://prnt.sc/j1u4m9](https://prnt.sc/j1u4m9)
