### ISSUE TITLE
Treinamento do algoritmo ao iniciar o servidor

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/image-processing-service#6]
João, para que este treinamento ocorra o que o servidor precisa fazer? Executar um script que gera um arquivo?

**Comment by joaoherrera** [comment]
Olá, Vitor.
Desenvolvi uma forma alternativa para que a o processo não necessite dos dados de treinamento em estado bruto. A rotina já foi testada e já está em funcionamento na versão atual. Obrigado.
