### ISSUE TITLE
Remover referência absoluta de scripts

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/image-processing-service#7]
É preciso que os scripts identifiquem o diretório base da aplicação sem o uso de referências absolutas, pois isto impede que seja feito o deploy em produção em um ambiente diferente do configurado no docker-compose deste repositório. O arquivos listados abaixo contém referências absolutas ao diretório `/src/script` e é preciso modificá-los:

- [ ] scripts/DeepLearning.py
- [ ] scripts/IO.py
- [ ] server/scheduler

**Comment by joaoherrera** [comment]
Vitor, modifiquei por enquanto os arquivos da pasta `/src/script` para que encontrem o caminho de forma dinâmica. Assim, não teríamos problemas tanto no novo ambiente quanto naquele configurado no `docker-compose`. Caso funcionar, me avise para que eu modifique o javascript localizado em `server/scheduler`
