### ISSUE TITLE
Documentar instalação no linux

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/image-processing-service#8]
É preciso fazer a documentação da instalação das dependências, sugiro usar o Ubuntu 16.04 LTS como referência.

**Comment by fititnt** [comment]
Por "documentar dependências" você diz instalando de forma direta no sistema operacional (ex.: em uma VM) ou dockerizado?

Em me disponho a ajudar com otimizar as questões de docker. Estou fazendo isso para outros projetos. Mas detalhes muito específicos da aplicação em si melhor deixar pra outra pessoa, pois não vou ser tão eficiente. Mas em ultimo caso posso fazer isso usando como base o Dockerfile.

O que posso fazer é liberar uma VM em algum lugar pra pessoa testar do zero e publicar os comandos.

**Comment by vgeorge** [comment]
Olá @fitint, o repositório já conta com uma máquina docker pronta para desenvolvimento, a idéia desta issue é facilitar a vida de quem quer subir o sistema sem usar o docker. Para construir os passos, eu recomendo usar o Vagrant ou Docker mesmo, mas qualquer outro sistema de VM serve. Desde que ofereça uma máquina Ubuntu LTS em seu ponto inicial após a instalação.

Eu fiz uma modificação recente no Dockerfile, que passou a contar com a instalação do Miniconda em invés do Anaconda, e isso ajudou a reduzir bastante o tamanho da máquina. Se identificar alguma melhoria possível é só mandar um PR.

Valeu!

**Comment by vgeorge** [comment]
A documentação de instalação local foi atualizada.
