### ISSUE TITLE
Script não retorna erro devido a problema de encoding

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/image-processing-service#9]
Voltou a aparecer um problema de encoding no arquivo errors.txt. Usando o branch `miniconda`, a execução da análise via shell da imagem inválida `samples/INVALID.jpeg` resulta o seguinte erro:

```
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Loading weights from /model/model_frcnn.hdf5
2018-04-09 20:07:51.910814: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Process started
/src/scripts/IO.py:83: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  errors = np.genfromtxt('scripts/Errors.txt', delimiter='$', dtype=None)
Traceback (most recent call last):
  File "scripts/Application.py", line 30, in <module>
    im = Utils.adjust_resolution(im)
  File "/src/scripts/Utils.py", line 62, in adjust_resolution
    print(IO.json_packing_error('ERR_008'))
  File "/src/scripts/IO.py", line 67, in json_packing_error
    erdesc = get_error_description(errcode)
  File "/src/scripts/IO.py", line 91, in get_error_description
    return description[idx][0].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 23: invalid continuation byte
```

Sugiro deixar de usar o arquivo `Errors.txt` e colocar as mensagens de erro dentro do script. Não vejo necessidade no momento em mantê-las em um arquivo separado e assim evitaríamos que o problema de enconding retorne.

**Comment by vgeorge** [comment]
Na verdade não são em todos em que o erro retornado é inválido, o erro de enquadramento está ok.

**Comment by joaoherrera** [comment]
@vgeorge a vantagem de utilizar o arquivo, neste caso, é a garantia de que o desenvolvedor, em uma eventual implementação ou correção, não misture diferentes códigos de erro e mensagens de erro. Não sei se você atualmente faz uso desse código. Optei por criá-lo pois caso haja a necessidade, por exemplo, de no futuro realizar um levantamento relacionado aos erros mais comuns que ocorrem durante a aquisição da amostra, não seja necessário trabalhar com as mensagens de erro propriamente ditas, e sim com seus respectivos códigos (apesar de que linguagens de alto nível facilitam bastante operações com strings). Portanto, preciso saber se pelo menos armazena o código do erro no banco. Caso contrário, vou ignorá-lo por enquanto e retornar apenas a mensagem.

**Comment by vgeorge** [comment]
@joaoherrera 

Tudo bem, podemos manter em um arquivo separado. O problema na verdade é que o script está sendo interrompido no caso que citei sem gerar uma mensagem de erro adequada. Isso faz com que a chamada do script pelo servidor retorne um erro inesperado, sem um código adequado. Veja como com fica no banco:

![captura de tela 2018-04-10 as 08 39 03](https://user-images.githubusercontent.com/329694/38554956-dc6a318a-3c9a-11e8-8c4f-d239be52c768.png)

**Comment by joaoherrera** [comment]
@vgeorge ao invés de mantê-los em um .txt, criei um método que os retorna conforme o código passado por argumento. Quanto ao encoding, a princípio não fiz modificações uma vez que retorno uma simples string (não leio aquivo nem nada) e por isso o python como padrão já é configurado como `utf-8`. Fiz um teste e na agendash a string está ok.
